spring:
  profiles:
    active:
      - dev
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
hoaxify:
  upload-path: uploads
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:hoaxify-dev
hoaxify:
  upload-path: uploads-dev
---


